services:
  - type: web
    name: licensing-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: licensing_system.db
      - key: PORT
        value: 10000
    disk:
      name: licensing-data
      mountPath: /opt/render/project/src
      sizeGB: 1
